# Generated by Django 5.0.6 on 2024-11-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookone',
            options={'verbose_name': 'Book One', 'verbose_name_plural': 'Book Ones'},
        ),
        migrations.AlterModelOptions(
            name='booktwo',
            options={'verbose_name': 'Book Two', 'verbose_name_plural': 'Book Twos'},
        ),
        migrations.AlterField(
            model_name='bookone',
            name='number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bookone',
            name='page',
            field=models.ImageField(upload_to='book_pages/'),
        ),
        migrations.AlterField(
            model_name='booktwo',
            name='number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booktwo',
            name='page',
            field=models.ImageField(upload_to='book_pages/'),
        ),
        migrations.AlterModelTable(
            name='bookone',
            table='book_one',
        ),
        migrations.AlterModelTable(
            name='booktwo',
            table='book_two',
        ),
    ]
