# Generated by Django 5.0.6 on 2024-11-17 07:48

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookone_options_alter_booktwo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookone',
            name='page',
            field=models.ImageField(upload_to='book_pages/', validators=[books.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='booktwo',
            name='page',
            field=models.ImageField(upload_to='book_pages/', validators=[books.models.validate_file_size]),
        ),
    ]
