# Generated by Django 5.0.6 on 2024-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='variant_size',
            field=models.IntegerField(default=1, verbose_name='Variant foto size'),
        ),
    ]
