# Generated by Django 5.0.6 on 2024-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizmodel_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='foto_three',
            field=models.ImageField(blank=True, null=True, upload_to='question', verbose_name='3-variant rasmi'),
        ),
    ]
