# Generated by Django 5.0.6 on 2024-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizmodel_created_at_quizmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='number',
            field=models.IntegerField(db_index=True, verbose_name='Savol Raqami'),
        ),
    ]
