# Generated by Django 5.0.6 on 2024-10-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='level',
            field=models.IntegerField(db_index=True, verbose_name='Savol Darajasi'),
        ),
    ]
