# Generated by Django 5.0.6 on 2024-10-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzko', '0002_vocabmodel_created_at_vocabmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabmodel',
            name='krill',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vocabmodel',
            name='korean',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vocabmodel',
            name='uzb',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
